# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('population', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countrydata.Continent')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='country',
            order_with_respect_to='name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='continent',
            order_with_respect_to='name',
        ),
    ]
